### ISSUE TITLE
Clustering > TODO PRIORITY

### ISSUE THREAD

**Issue by FALL1N1** [ProjectBalnaZZar/Issue-Tracker#23]
- [ ] Cross-node character loading (getting 'unknown' names)
- [ ] Instances - groups.
- [ ] Remove worldsession delay
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by FALL1N1** [comment]
group

- [ ] store id
- [ ] proxy <> node communication
- [ ] playerdata
- [ ] chat(raid,raidwarning,party,raidlead)
- [ ] node preload / Player::PerformNodeChangeStuff
