### ISSUE TITLE
TODO LIST / WIP

### ISSUE THREAD

**Issue by FALL1N1** [ProjectBalnaZZar/Issue-Tracker#4]
# Armory
- Character
- [x] ARMORY: Char listing
- [x] ARMORY: Char pageItems
- [ ] ARMORY: Char pageTalents
- [x] ARMORY: Char pageGlyphs
- [x] ARMORY: Char pageAchievements
- [x] ARMORY: Char pageLLi (LastLootedItems)
- [ ] ARMORY: Char pageRaid Encounters
- [x] ARMORY: Char pageArena Ranking

- Guild
- [ ] ARMORY: Guild PageListing
- [ ] ARMORY: Guild PageMember List + Rank
- [ ] ARMORY: Guild PageInfo?
- [ ] ARMORY: Guild PageMotd?
- [ ] ARMORY: Guild PageSort by rank? 
- Arena

- [ ] ARMORY: Arena PageLast 10 games listing?
- [ ] ARMORY: Arena PageExpand arena match (damage done, healing done, AT-style)

- Raid

- [ ] ARMORY: Raid pageTop 10 raid clears?
- [ ] ARMORY: Raid pagePlayer history of X encounter (damage taken, damage done, deaths, spell hits.. [GRAPH]) 

 ---
- [x] Register
- [ ] Login
- [x] News
- [x] Slider
- [ ] 404
- [ ] Forum (phpbb?)

**Comment by FALL1N1** [comment]
moved to #8
